{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "awsproject.serviceAccountName" . }}
  labels:
{{ include "awsproject.labels" . | indent 4 }}
{{- end -}}
